# Site settings
title: IoT.js
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A framework for Internet of Things.
# baseurl: "/iotjstest" # the subpath of your site, e.g. /blog/
# url: "http://hs0225.github.io" # the base hostname & protocol for your site
#twitter_username:
#github_username:  samsung

# Build settings
highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM